2) Perform all linear algebra operation with Tensorflow.

In [1]:
import tensorflow as tf
import numpy as np
A=tf.constant([[4.7,9.5],
              [3.3,6]])
B=tf.constant([[5.5,7.8],
              [3.9,4.7]])

C:\Users\amees\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
print(tf.add(A,B))
print(tf.subtract(A,B))
print(tf.multiply(A,B))

tf.Tensor(
[[10.2 17.3]
 [ 7.2 10.7]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.8000002   1.6999998 ]
 [-0.60000014  1.3000002 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[25.849998 74.1     ]
 [12.87     28.199999]], shape=(2, 2), dtype=float32)


In [3]:
print(tf.matmul(A,B))
print(tf.tensordot(A,B,1))

tf.Tensor(
[[62.899998 81.31    ]
 [41.550003 53.94    ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[62.899998 81.31    ]
 [41.550003 53.94    ]], shape=(2, 2), dtype=float32)


In [4]:
print(tf.transpose(A))
print(tf.linalg.det(A))
print(tf.linalg.inv(A))

tf.Tensor(
[[4.7 3.3]
 [9.5 6. ]], shape=(2, 2), dtype=float32)
tf.Tensor(-3.150002, shape=(), dtype=float32)
tf.Tensor(
[[-1.9047606  3.0158708]
 [ 1.0476184 -1.4920624]], shape=(2, 2), dtype=float32)


In [5]:
x=tf.constant([[5.3],
               [8.4]])
print(tf.linalg.solve(A,x))
print(tf.norm(x,ord=2))

tf.Tensor(
[[15.238083]
 [-6.980946]], shape=(2, 1), dtype=float32)
tf.Tensor(9.93227, shape=(), dtype=float32)


In [6]:
print(tf.linalg.eigh(A))
print(tf.linalg.svd(A,full_matrices=False))

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.9865935, 8.713404 ], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.77241707, -0.6351155 ],
       [ 0.6351155 , -0.77241707]], dtype=float32)>)
(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([12.616167  ,  0.24968004], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.84004843, -0.54251146],
       [ 0.54251146,  0.84004843]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.45485407,  0.890566  ],
       [ 0.890566  , -0.45485407]], dtype=float32)>)


3) Write a program to implement AND OR gates using Perceptron.

In [8]:
import torch
import torch.nn as nn
import torch.optim as optim

# Inputs: [0,0], [0,1], [1,0], [1,1]
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)

# Targets for AND Gate
y_and = torch.tensor([[0], [0], [0], [1]], dtype=torch.float32)

# Targets for OR Gate
y_or = torch.tensor([[0], [1], [1], [1]], dtype=torch.float32)

# 2. Define the Perceptron Model
class Perceptron(nn.Module):
    def __init__(self):
        super(Perceptron, self).__init__()
        self.linear = nn.Linear(2, 1)
        self.activation = nn.Sigmoid()

    def forward(self, x):
        return self.activation(self.linear(x))

def train_gate(model, X, y, gate_name, epochs=1000):
    optimizer = optim.SGD(model.parameters(), lr=0.1)
    criterion = nn.BCELoss()

    print(f"\n--- Training {gate_name} Gate ---")

    for epoch in range(epochs):
        # Forward pass
        outputs = model(X)
        loss = criterion(outputs, y)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (epoch+1) % 200 == 0:
            print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

    return model
model_and = Perceptron()
train_gate(model_and, X, y_and, "AND")

print("\nAND Gate Predictions:")
with torch.no_grad():
    predictions = model_and(X)
    predicted_classes = predictions.round()
    for i in range(len(X)):
        print(f"Input: {X[i].numpy()} -> Prediction: {predicted_classes[i].item()}")

model_or = Perceptron()
train_gate(model_or, X, y_or, "OR")

print("\nTesting OR Gate Predictions:")
with torch.no_grad():
    predictions = model_or(X)
    predicted_classes = predictions.round()
    for i in range(len(X)):
        print(f"Input: {X[i].numpy()} -> Prediction: {predicted_classes[i].item()}")


--- Training AND Gate ---
Epoch [200/1000], Loss: 0.4071
Epoch [400/1000], Loss: 0.2793
Epoch [600/1000], Loss: 0.2156
Epoch [800/1000], Loss: 0.1762
Epoch [1000/1000], Loss: 0.1491

AND Gate Predictions:
Input: [0. 0.] -> Prediction: 0.0
Input: [0. 1.] -> Prediction: 0.0
Input: [1. 0.] -> Prediction: 0.0
Input: [1. 1.] -> Prediction: 1.0

--- Training OR Gate ---
Epoch [200/1000], Loss: 0.2826
Epoch [400/1000], Loss: 0.1901
Epoch [600/1000], Loss: 0.1414
Epoch [800/1000], Loss: 0.1118
Epoch [1000/1000], Loss: 0.0920

Testing OR Gate Predictions:
Input: [0. 0.] -> Prediction: 0.0
Input: [0. 1.] -> Prediction: 1.0
Input: [1. 0.] -> Prediction: 1.0
Input: [1. 1.] -> Prediction: 1.0


In [10]:
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
y = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32)
class XORModel(nn.Module):
    def __init__(self):
        super(XORModel, self).__init__()
        # We need at least 2 hidden neurons to solve XOR
        self.hidden = nn.Linear(2, 2)
        self.activation_hidden = nn.Sigmoid()
        self.output = nn.Linear(2, 1)
        self.activation_output = nn.Sigmoid()

    def forward(self, x):
        # Pass through hidden layer
        x = self.hidden(x)
        x = self.activation_hidden(x)

        # Pass through output layer
        x = self.output(x)
        x = self.activation_output(x)
        return x

model = XORModel()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)
epochs = 3000

for epoch in range(epochs):
    optimizer.zero_grad()

    outputs = model(X)
    loss = criterion(outputs, y)

    loss.backward()
    optimizer.step()

    if (epoch+1) % 500 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')
print("/nPredictions")
with torch.no_grad():
    predictions = model(X)
    predicted_classes = predictions.round()

    for i in range(len(X)):
        input_val = X[i].numpy()
        pred = predicted_classes[i].item()
        target = y[i].item()
        print(f"Input: {input_val} | Target: {target} | Prediction: {pred}")

Epoch [500/3000], Loss: 0.0027
Epoch [1000/3000], Loss: 0.0009
Epoch [1500/3000], Loss: 0.0004
Epoch [2000/3000], Loss: 0.0003
Epoch [2500/3000], Loss: 0.0002
Epoch [3000/3000], Loss: 0.0001
/nPredictions
Input: [0. 0.] | Target: 0.0 | Prediction: 0.0
Input: [0. 1.] | Target: 1.0 | Prediction: 1.0
Input: [1. 0.] | Target: 1.0 | Prediction: 1.0
Input: [1. 1.] | Target: 0.0 | Prediction: 0.0


In [16]:
import torch
import torch.nn as nn
import torch.optim as optim

true_equation = lambda x: 2 * x[:, 0] + 3 * x[:, 1] + 5

def generate_data(num_samples):
    X = torch.rand(num_samples, 2) * 10
    y = true_equation(X)
    y = y.view(-1, 1)
    return X, y

torch.manual_seed(42)
X_train, y_train = generate_data(100)
X_val, y_val = generate_data(20)

print(f"Target Equation: y = 2*x1 + 3*x2 + 5")

class RegressionNet(nn.Module):
    def __init__(self):
        super(RegressionNet, self).__init__()
        # Input (2) -> Hidden (2)
        self.hidden = nn.Linear(2, 2)
        self.activation = nn.Sigmoid()

        # Hidden (2) -> Output (1)
        self.output = nn.Linear(2, 1)

    def forward(self, x):
        x = self.hidden(x)
        x = self.activation(x)
        x = self.output(x)
        return x

model = RegressionNet()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.05)

print("\nTraining:")
epochs = 2000

for epoch in range(epochs):
    model.train()

    # Forward pass
    predictions = model(X_train)
    loss = criterion(predictions, y_train)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 500 == 0:
        print(f'Epoch [{epoch+1}/{epochs}] | Train Loss: {loss.item():.4f}')

print("\nValidation:")
model.eval()

with torch.no_grad():
    val_predictions = model(X_val)
    val_loss = criterion(val_predictions, y_val)

    print(f"Validation MSE Loss: {val_loss.item():.4f}")
    print("\nFirst 5 validation predictions:")
    print(f"{'Input (x1, x2)':<20} | {'Predicted':<12} | {'Actual (y)':<12} | {'Diff':<10}")
    for i in range(5):
        x_vals = f"[{X_val[i][0]:.1f}, {X_val[i][1]:.1f}]"
        pred = val_predictions[i].item()
        actual = y_val[i].item()
        diff = abs(pred - actual)

        print(f"{x_vals:<20} | {pred:<12.4f} | {actual:<12.4f} | {diff:<10.4f}")

Target Equation: y = 2*x1 + 3*x2 + 5

Training:
Epoch [500/2000] | Train Loss: 11.5819
Epoch [1000/2000] | Train Loss: 1.9583
Epoch [1500/2000] | Train Loss: 1.1673
Epoch [2000/2000] | Train Loss: 0.9265

Validation:
Validation MSE Loss: 3.0367

First 5 validation predictions:
Input (x1, x2)       | Predicted    | Actual (y)   | Diff      
[0.5, 3.2]           | 15.2728      | 15.3819      | 0.1091    
[9.2, 6.9]           | 44.5073      | 44.2646      | 0.2427    
[4.8, 2.0]           | 19.8704      | 20.4590      | 0.5886    
[1.9, 0.5]           | 13.1746      | 10.4454      | 2.7291    
[3.4, 6.7]           | 31.6113      | 31.8059      | 0.1946    
